type CategoryResponse {
    uuid: ID!
    name: String!
    description: String!
    icon: String
}

type CategoryPaginate {
    content: [CategoryResponse]!
    empty: Boolean
    first: Boolean
    last: Boolean
    number: Int
    numberOfElements: Int
    size: Int
    totalElements: Int
    totalPages: Int
}

input CategoryRequest {
    name: String!
    description: String!
    icon: String
}

input CategoryFilterQueryParamInput {
    field: String = "ALL"
    search: String
    pageSize: Int = 10
    pageNumber: Int = 0
}
