type ReservationResponse {
    uuid: ID!
    type: String!
    date: String!
    hour: String!
    product: ProductResponse
    user: UserResponse
}

type ReservationPaginate {
    content: [ReservationResponse]!
    empty: Boolean
    first: Boolean
    last: Boolean
    number: Int
    numberOfElements: Int
    size: Int
    totalElements: Int
    totalPages: Int
}

input ReservationRequest {
    productUuid: ID!
    userUuid: ID!
    type: String!
    date: String!
    hour: String!
}

input ReservationFilterQueryParamInput {
    field: String = "ALL"
    search: String
    pageSize: Int = 10
    pageNumber: Int = 0
}
