server:
  error:
    include-stacktrace: never
    include-binding-errors: always
    include-message: always
spring:
  application:
    name: negoreserva
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  graphql:
    graphiql:
      enabled: true
  threads:
    virtual:
      enabled: true
  mvc:
    problem-details:
      enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
spring-doc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
crypto:
  secret-key: classpath:certs/secret.pem
  salt: a1b2c3d4e5f60011
ombala:
  api:
    base-url: ${OMBALA_BASE_URL}
    token: ${OMBALA_TOKEN}
    name: ${OMBALA_FROM}
mailjet:
  api:
    base-url: ${MAILJET_BASE_URL}
    public-key: ${MAILJET_PUBLIC_KEY}
    private-key: ${MAILJET_PRIVATE_KEY}
  sender:
    name: ${MAILJET_NAME}
    email: ${MAILJET_EMAIL}
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}