extend type Query {
    adminPaginateUser(paginateRequest: PaginateRequest): UserPaginate!
    adminPaginateUserFilter(filter: UserFilterQueryParamInput): UserPaginate!
    adminFindByUuidUser(uuid: ID!): UserResponse
    adminFindByEmailUser(email: String!): UserResponse
    adminFindByPhoneUser(phone: String!): UserResponse
}

extend type Mutation {
    adminSaveUser(userCreateRequest: UserCreateRequest!): UserResponse
    adminUpdateUser(uuid: ID!, userUpdateRequest: UserUpdateRequest!): UserResponse
    adminDeleteByUuidUser(uuid: ID!): Boolean
}