type DashboardTotals {
    totalProducts: Int!
    totalPayments: Int!
    totalCatalogs: Int!
}

type DashboardCatalogWithProductCount {
    uuid: ID!
    name: String!
    description: String!
    imgUrl: String
    slug: String!
    productCount: Int!
}

type DashboardPaymentByStatus {
    paymentStatus: String!
    count: Int!
}

type DashboardPaymentByMethod {
    paymentMethod: String!
    count: Int!
}

extend type Query {
    orgDashboardTotals: DashboardTotals!
    orgDashboardCatalogsWithProductCount: [DashboardCatalogWithProductCount]!
    orgDashboardPaymentsByStatus: [DashboardPaymentByStatus]!
    orgDashboardPaymentsByMethod: [DashboardPaymentByMethod]!
    orgDashboardRecentPayments(pageSize: Int = 5): [OrgPaymentResponse]!
    orgDashboardRecentProducts(pageSize: Int = 5): [OrgProductResponse]!
    orgDashboardRecentCatalogs(pageSize: Int = 5): [OrgCatalogResponse]!
}
