type OrgReservationResponse {
    uuid: ID!
    type: String!
    date: String!
    hour: String!
}

type OrgReservationPaginate {
    content: [OrgReservationResponse]!
    empty: Boolean
    first: Boolean
    last: Boolean
    number: Int
    numberOfElements: Int
    size: Int
    totalElements: Int
    totalPages: Int
}

extend type Query {
    orgPaginateReservation(paginateRequest: PaginateRequest): OrgReservationPaginate!
    orgPaginateReservationFilter(filter: ReservationFilterQueryParamInput): OrgReservationPaginate!
    orgFindByUuidReservation(uuid: ID!): OrgReservationResponse
}

extend type Mutation {
    orgSaveReservation(reservationRequest: ReservationRequest!): OrgReservationResponse
    orgUpdateReservation(uuid: ID!, reservationRequest: ReservationRequest!): OrgReservationResponse
    orgDeleteByUuidReservation(uuid: ID!): Boolean
}
